<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Veterinarian Dashboard for Zoo Arcadia">
    <meta name="keywords" content="zoo, veterinarian dashboard, animal care, animal health">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Veterinarian Dashboard</title>

    <link rel="stylesheet" href="/node_modules/Normalize-css/normalize.css" />
    <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="build/css/app.css">
</head>

<body class="veterinarian-dashboard">
    <header class="navbar navbar-expand-lg navbar-dark bg-dark sticky-md-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Zoo Arcadia - Veterinarian Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="#health-report">Health Report</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#nutrition">Propose Nutrition</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#habitat-suggestions">Habitat Suggestions</a>
                    </li>
                </ul>
            </div>
        </div>
    </header>

    <main class="container my-4">
        <!-- Health Report Section -->
        <section id="health-report" class="mb-5">
            <h2 class="mb-4">Complete Health Report</h2>
            <div class="card shadow-sm">
                <div class="card-body">
                    <form>
                        <div class="mb-3">
                            <label for="animal-search" class="form-label">Filter animal by:</label>
                            <input type="text" class="form-control mb-2" id="animal-search"
                                placeholder="Search animal by name...">
                            <div class="mb-3">
                                <label for="filters" class="form-label">Filter Faster</label>
                                <div class="d-flex flex-wrap gap-3">
                                    <select class="form-select w-auto" id="habitat-filter">
                                        <option selected disabled>Habitat</option>
                                        <option value="savannah">Savannah</option>
                                        <option value="jungle">Jungle</option>
                                        <option value="swamp">Swamp</option>
                                    </select>
                                    <select class="form-select w-auto" id="classes-filter">
                                        <option selected disabled>classes</option>
                                        <option value="mammal">Mammal</option>
                                        <option value="bird">Bird</option>
                                        <option value="reptile">Reptile</option>
                                    </select>
                                    <select class="form-select w-auto" id="nutrition-filter">
                                        <option selected disabled>Nutrition</option>
                                        <option value="carnivore">Carnivore</option>
                                        <option value="herbivore">Herbivore</option>
                                        <option value="omnivore">Omnivore</option>
                                    </select>
                                    <select class="form-select w-auto" id="status-filter">
                                        <option selected disabled>Status</option>
                                        <option value="healthy">Healthy</option>
                                        <option value="sick">Sick</option>
                                        <option value="quarantined">Quarantined</option>
                                    </select>
                                </div>
                            </div>
                            <div id="filter-results" class="mt-3">
                                <!-- animal generated by filter -->
                                <div class="card mb-3">
                                    <div class="card-body">
                                        <h5 class="card-title">Assign nutrition to Animal Filtered</h5>
                                        <p class="card-text">Name: <span id="animal-name">-</span></p>
                                        <p class="card-text">Bread: <span id="animal-bread">-</span></p>
                                        <p class="card-text">Habitat: <span id="animal-habitat">-</span></p>
                                        <p class="card-text">Last Meal: <span id="last-meal">-</span></p>
                                        <p class="card-text">Quantity of Meal: <span id="last-quantity">-</span></p>
                                        <p class="card-text">Last Date to Feed: <span id="last-date">-</span></p>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mb-3">Accept animal</button>
                            <button class="btn btn-danger mb-3">Reset</button>
                        </div>
                        <hr class="mb-4">

                        <div class="mb-3">
                            <label for="animal-status" class="form-label">Animal Status</label>
                            <select class="form-select w-auto" id="animal-status">
                                <option selected disabled>Status</option>
                                <option value="healthy">Healthy</option>
                                <option value="sick">Sick</option>
                                <option value="quarantined">Quarantined</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="review-date" class="form-label">Review Date</label>
                            <input type="datetime-local" class="form-control" id="review-date">
                        </div>
                        <div class="mb-3">
                            <label for="health-details" class="form-label">Health Details</label>
                            <textarea class="form-control" id="health-details" rows="3"
                                placeholder="Provide detailed health information"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="vet-opinion" class="form-label">Veterinarian Opinion</label>
                            <textarea class="form-control" id="vet-opinion" rows="3"
                                placeholder="Share your professional opinion"></textarea>
                        </div>
                        <!-- Propose Nutrition Section -->
                        <h3 id="nutrition" class="mb-3">Propose Nutrition</h3>
                        <div class="mb-3">
                            <label for="proposed-nutrition-type" class="form-label">Proposed Nutrition</label>
                            <select class="form-select" id="proposed-nutrition-type">
                                <option selected disabled>Choose food type</option>
                                <option value="meat">Meat</option>
                                <option value="vegetables">Vegetables</option>
                                <option value="fruits">Fruits</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="nutrition-quantity" class="form-label">Quantity (grams)</label>
                            <input type="number" class="form-control" id="nutrition-quantity"
                                placeholder="Enter quantity in grams">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit Report</button>
                        <button class="btn btn-danger">Reset</button>

                    </form>
                </div>
            </div>
        </section>


        <!-- Habitat Improvement Suggestions Section -->
        <section id="habitat-suggestions" class="mb-5">
            <h2 class="mb-4">Suggest Habitat Improvements</h2>
            <div class="card shadow-sm">
                <div class="card-body">
                    <form>
                        <div class="mb-3">
                            <label for="habitat-selection" class="form-label">Select Habitat</label>
                            <select class="form-select" id="habitat-selection">
                                <option selected disabled>Choose a habitat</option>
                                <option value="savannah">Savannah</option>
                                <option value="jungle">Jungle</option>
                                <option value="swamp">Swamp</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="improvement-suggestion" class="form-label">Improvement Suggestion</label>
                            <textarea class="form-control" id="improvement-suggestion" rows="3"
                                placeholder="Provide your suggestion"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit Suggestion</button>
                        <button class="btn btn-danger">Reset</button>

                    </form>
                </div>
            </div>
        </section>



    </main>

    <footer class="bg-dark text-white py-3 mt-5 fixed-bottom">
        <div class="container text-center">
            <p>&copy; 2024 Zoo Arcadia. All rights reserved.</p>
        </div>
    </footer>

    <script type="module" src="/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>